apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
#It's db.
  - name: db
    image: mysql:5.6.50
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: "exampledb"
    - name: MYSQL_USER
      value: "user "
    - name: MYSQL_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "1028Mi" #太小會失敗...
        cpu: "500m"
#檢查MYSQL db是不是活著
    livenessProbe:
      tcpSocket:
        port: 3306
#It's is wp.
  - name: wp
    image: wordpress:php8.0-apache
    env:
    - name: WORDPRESS_DB_HOST
      value: "127.0.0.1:3306"
    - name: WORDPRESS_DB_USER
      value: "user"
    - name: WORDPRESS_DB_PASSWORD
      value: "password"
    - name: WORDPRESS_DB_NAME
      value: "exampledb"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "1028Mi" #太小會失敗...
        cpu: "500m"
#檢查WORDPRESS是不是活著 偵測錯誤會被重啟
    livenessProbe:
      httpGet:
        path: /
        port: 80
        scheme: HTTP
#檢查MYSQL db失敗的時後 WORDPRESS不處理新的請求
    readinessProbe:
      tcpSocket:
        port: 3306
  dnsPolicy: ClusterFirst
  restartPolicy: Always
